// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh_DalSNZmr4GRrhmF8ssc1FuJPcoD1Rc',
    appId: '1:803562556288:web:05c6c4d6cb126e7f478f65',
    messagingSenderId: '803562556288',
    projectId: 'pokedexkingtide',
    authDomain: 'pokedexkingtide.firebaseapp.com',
    storageBucket: 'pokedexkingtide.appspot.com',
    measurementId: 'G-9T2RRC6H7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOD6qU1HnunwLX1s4PwGIZIS17-AAHy58',
    appId: '1:803562556288:android:a121dffac2fcfed3478f65',
    messagingSenderId: '803562556288',
    projectId: 'pokedexkingtide',
    storageBucket: 'pokedexkingtide.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbBO2mIud1heBxsQ9115t3LUM5hoF4FDc',
    appId: '1:803562556288:ios:81bd478edd4251ee478f65',
    messagingSenderId: '803562556288',
    projectId: 'pokedexkingtide',
    storageBucket: 'pokedexkingtide.appspot.com',
    iosBundleId: 'com.kingtide.pokedex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbBO2mIud1heBxsQ9115t3LUM5hoF4FDc',
    appId: '1:803562556288:ios:bfa016571498be70478f65',
    messagingSenderId: '803562556288',
    projectId: 'pokedexkingtide',
    storageBucket: 'pokedexkingtide.appspot.com',
    iosBundleId: 'com.kingtide.pokedex.RunnerTests',
  );
}
